services:
  chatgpt-ui:
    image: vectorchai/chatbot-ui:latest
    hostname: chatbot-ui
    container_name: chatbot-ui
    restart: unless-stopped
    ports:
      - 40113:3000
    environment:
      - OPENAI_API_HOST=http://gpu3.talic.hku.hk:3000
      - OPENAI_API_KEY=talic
      - DEFAULT_MODEL=NousResearch/Meta-Llama-3-8B-Instruct-GGUF
      - DEFAULT_SYSTEM_PROMPT=You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.