services:
  chatgpt-ui:
    build:
      context: ./
    hostname: chatbot-ui
    container_name: chatbot-ui
    restart: unless-stopped
    ports:
      - 40113:3000
    environment:
      - OPENAI_API_HOST=http://gpu1.talic.hku.hk:40113
      - OPENAI_API_KEY=talic
      - DEFAULT_MODEL=cognitivecomputations/dolphin-2.9-llama3-8b-256k
      - DEFAULT_SYSTEM_PROMPT=You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.